name: Deploy

on:
  push:
    branches:
      - develop
      - feature/lint-frontend-ci
  workflow_dispatch:
      
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clear Destination Directory
        run: rm -rf /var/repository/*
      - name: Copy Sources
        run: cp -a . /var/repository/
  build:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Setup Environment
        working-directory: /var/repository/
        run: |
          echo "VITE_API_BASE_URL=${{ vars.VITE_API_BASE_URL }}" > frontend/.env
      - name: Build Containers
        working-directory: /var/repository/
        run: docker compose up -d --build
  deploy:
    runs-on: self-hosted
    needs: [checkout, build]
    steps:
      - name: Restart Web Server
        working-directory: /var/repository/
        run: docker compose restart caddy
